version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: fluxoalpha-postgres
    environment:
      POSTGRES_DB: webhook_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine # O '-management' traz o painel visual!
    container_name: fluxoalpha-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: adminpassword
    ports:
    - "5673:5672"   # Porta de comunicação com o Spring Boot
    - "15673:15672" # Porta do painel visual no navegador

volumes:
  postgres_data: