spring.application.name=desafio-webhook-processor
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:postgresql://localhost:5433/webhook_db
spring.datasource.username=admin
spring.datasource.password=adminpassword
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5673
spring.rabbitmq.username=admin
spring.rabbitmq.password=adminpassword

# --- Resiliência e DLQ ---
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=2000
spring.rabbitmq.listener.simple.retry.max-retries=3